package io.github.nebula.ktx.cli

import io.github.nebula.ktx.cli.meta.ScriptToolchain
import io.github.nebula.ktx.cli.meta.ToolchainHeaderScanner
import io.github.nebula.ktx.toolchain.JdkInstall
import io.github.nebula.ktx.toolchain.ToolchainStore
import org.slf4j.LoggerFactory
import java.nio.file.Path

/**
 * Handles the script-declared `@file:Toolchain(jdk = "...")`:
 *
 *   1. Read the JDK major version declared by the script;
 *   2. Compare with the current JVM major version; if mismatched, ensure that
 *      JDK is installed (auto-download on demand);
 *   3. Re-exec ktx with the target JDK (sets JAVA_HOME), forwarding original args.
 *
 * **Recursion guard**: the env var `KTX_TOOLCHAIN_DISPATCHED=1` marks that a
 * re-exec has already happened. A child process seeing this variable skips
 * routing and runs on the current JVM, even if its version doesn't match the
 * script's declaration (the previous routing or install must have failed; we
 * report and don't loop).
 */
object ToolchainDispatcher {

    private val log = LoggerFactory.getLogger("ktx.cli.dispatch")

    private const val DISPATCH_ENV = "KTX_TOOLCHAIN_DISPATCHED"

    /**
     * If the script requires a JDK other than the one ktx is running on,
     * **re-exec the current process with that JDK and never return**.
     * Otherwise return so RunCommand continues normally.
     *
     * @param scriptPath script path to scan for `@file:Toolchain`.
     * @param store injected for testability.
     */
    fun dispatchIfNeeded(scriptPath: Path, store: ToolchainStore = ToolchainStore()) {
        if (System.getenv(DISPATCH_ENV) != null) {
            log.debug("already a dispatched child, skip toolchain routing")
            return
        }

        val tc = ToolchainHeaderScanner.scan(scriptPath)
        val majorRequested = parseMajor(tc) ?: return  // script did not declare jdk
        val majorCurrent = currentJvmMajor()

        if (majorRequested == majorCurrent) {
            log.debug("current JVM major {} already matches script declaration, no switch needed", majorCurrent)
            return
        }

        val install = store.find(majorRequested) ?: run {
            log.info("script requires JDK {}, not installed locally, downloading", majorRequested)
            store.install(majorRequested)
        }

        log.info("switching to JDK {} ({})", majorRequested, install.javaHome)
        reExec(install)
    }

    private fun parseMajor(tc: ScriptToolchain): Int? =
        tc.jdk.takeIf { it.isNotEmpty() }
            ?.let { it.substringBefore('.').toIntOrNull() }
            ?: run {
                if (tc.jdk.isNotEmpty()) {
                    log.warn("cannot parse major version from @file:Toolchain(jdk = \"{}\"), ignored", tc.jdk)
                }
                null
            }

    /**
     * Current JVM major version. `Runtime.version().feature()` always returns
     * the major (21, 17, ...) on JDK 9+, no string parsing needed.
     */
    private fun currentJvmMajor(): Int = Runtime.version().feature()

    /**
     * Restart ktx with [install]; **does not return**.
     *
     * Implementation: locate the current ktx launcher script (env var /
     * sun property / heuristic), spawn a child with [ProcessBuilder],
     * inheritIO, then exit with the child's exit code.
     *
     * Why not `execve()`: calling `execve` from inside a JVM requires JNI,
     * and JVM exit may stall on shutdown hooks. fork + wait is more portable;
     * the cost is one extra (short-lived) process worth of memory.
     */
    private fun reExec(install: JdkInstall): Nothing {
        val launcher = locateLauncherScript()
            ?: error(
                "Cannot locate ktx launcher script to re-dispatch to JDK ${install.majorVersion}. " +
                    "Make sure ktx is started via the bin/ktx generated by installDist, not direct java -jar.",
            )

        // Forward original argv: JVM main(args) sees args, but not the script
        // path of the current process. We could use ProcessHandle.current().info()
        // .arguments() (which includes everything after the launcher), but it
        // sometimes returns empty on macOS, so we fall back to the in-memory copy
        // ktx itself stashed at startup (Main.kt).
        val args = OriginalArgs.value()
            ?: error("original argv not captured (OriginalArgs.set not called in Main?)")

        val cmd = listOf(launcher.toAbsolutePath().toString()) + args
        val pb = ProcessBuilder(cmd)
            .redirectErrorStream(false)
            .redirectInput(ProcessBuilder.Redirect.INHERIT)
            .redirectOutput(ProcessBuilder.Redirect.INHERIT)
            .redirectError(ProcessBuilder.Redirect.INHERIT)
        pb.environment()["JAVA_HOME"] = install.javaHome.toAbsolutePath().toString()
        pb.environment()[DISPATCH_ENV] = "1"

        log.debug("re-exec: {}", cmd.joinToString(" "))
        val proc = pb.start()
        val exitCode = proc.waitFor()
        kotlin.system.exitProcess(exitCode)
    }

    /**
     * Locate the `bin/ktx` launcher script. Resolution order:
     *   1. env var `KTX_LAUNCHER` (dev-time or future daemon self-report);
     *   2. `org.gradle.appname` system property + executable location heuristic;
     *   3. follow `Class.getProtectionDomain().codeSource.location` to the jar,
     *      walk back to the install root, look for `bin/ktx`.
     */
    private fun locateLauncherScript(): Path? {
        System.getenv("KTX_LAUNCHER")?.takeIf { it.isNotBlank() }?.let { return Path.of(it) }

        // The Gradle Application launcher script sets APP_HOME
        System.getenv("APP_HOME")?.takeIf { it.isNotBlank() }?.let {
            val candidate = Path.of(it, "bin", "ktx")
            if (candidate.toFile().exists()) return candidate
        }

        // Walk back from the jar path: lib/cli-*.jar's grandparent is the install root
        val codeSource = ToolchainDispatcher::class.java.protectionDomain?.codeSource?.location
            ?: return null
        val jarFile = Path.of(codeSource.toURI())
        val installRoot = jarFile.parent?.parent ?: return null
        val candidate = installRoot.resolve("bin/ktx")
        return if (candidate.toFile().exists()) candidate else null
    }
}

/**
 * Called from the process entry point ([Main.main]) via [set] to stash a copy
 * of the original argv for later re-exec. More reliable than
 * `ProcessHandle.current().info().arguments()`, which often returns empty on macOS.
 */
internal object OriginalArgs {
    private var args: Array<String>? = null
    fun set(args: Array<String>) {
        this.args = args
    }

    fun value(): List<String>? = args?.toList()
}
